CREATE TABLE IF NOT EXISTS studio (
  id BIGINT PRIMARY KEY AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  row_count INT NOT NULL,
  col_count INT NOT NULL,
  introduction VARCHAR(2000),
  status TINYINT NOT NULL DEFAULT 1,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  KEY idx_studio_status (status),
  KEY idx_studio_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
